### ISSUE TITLE
Add this (additional) agency data into the data set. 

### ISSUE THREAD

**Issue by allalala** [18F/forecast#19]
Client is very interested in showing GSA _and_ Dept of Education _and_ Dept of State data. Please load this data so that it is sortable during the next demo of the MVP. 

[DepEducation-OpenOpportunities-Forcecast.xlsx](https://github.com/18F/osbu-forecast-api/files/50213/DepEducation-OpenOpportunities-Forcecast.xlsx)
[DeptState-FY15-Opportunities-235609.xlsx](https://github.com/18F/osbu-forecast-api/files/50212/DeptState-FY15-Opportunities-235609.xlsx)

**Comment by vdavez** [comment]
@ddotrollins do you have a sense of how the wireframe might change so that we could allow a filter of the data?

**Comment by ddotrollins** [comment]
@vzvenyach Do you have a sense of which filters are the most important to bring forward? It was hard for me to determine how to prioritize something like the Place, NAICS Code, or Contract Type, etc. There will probably be a few filters brought out and then a more advanced state.

**Comment by vdavez** [comment]
I found this artifact from an initial interview of the Product Owner, and it suggests that the key filters (in order) are:
1. award status
2. NAICS code
3. City/State
4. Award amount
5. Solicitation date

![img_0437](https://cloud.githubusercontent.com/assets/4153048/11564492/5b582e96-998e-11e5-84f0-62b6011e9801.jpg)

**Comment by ddotrollins** [comment]
@vzvenyach here's how I would handle filters given the new info. Also, it seems like there is a need to make this easier to share results with others either via link or maybe creating a custom report (i.e. a spreadsheet with only the filtered items shown). I would add either of those to the feature backlog and we can consider how we may implement that in the future but for now it may not be as necessary.

![g - alt view filters](https://cloud.githubusercontent.com/assets/9273855/11567624/d010c802-99b5-11e5-9efe-11284f2266c1.png)

**Comment by vdavez** [comment]
Going to close this issue for now.
