### ISSUE TITLE
As an admin, I need the 18F and DAP Google Analytics codes to track visitors.

### ISSUE THREAD

**Issue by vdavez** [18F/forecast#20]
XPOST from https://github.com/18F/osbu-forecast/issues/6

**Comment by gbinal** [comment]
For 18F, check in at `#g-analytics` on slack.  We'll need to know there the URL for the site.  

For DAP, you'll find the right snippet here - https://github.com/18f/analytics-standards#digital-analytics-program-snippet

**Comment by stvnrlly** [comment]
Done in https://github.com/18F/forecast/pull/25.
