### ISSUE TITLE
Drawing a top-level diagram of the system architecture

### ISSUE THREAD

**Issue by stvnrlly** [18F/forecast#34]
See https://pages.18f.gov/before-you-ship/ato/.

**Comment by stvnrlly** [comment]
![system](https://cloud.githubusercontent.com/assets/4156602/12244477/cfe19c46-b871-11e5-9ddb-5e2e6fc2b16f.png)

**Comment by allalala** [comment]
:+1:

**Comment by NoahKunin** [comment]
Just confirming :+1: too

**Comment by allalala** [comment]
@NoahKunin does this mean we have begun the ATO process?
