### ISSUE TITLE
Incorrect margin-right on main section

### ISSUE THREAD

**Issue by noahmanger** [18F/forecast#71]
I noticed that when I first load the page, `<section class="usa-width-three-fourths">` still has its `margin-right` value set, which causes it to fall below the filters, rather than next to it. Eventually, once the page is loaded, the correct `:last-child { margin-right: 0 }` property gets set. I can't tell why it's doing this, but wanted to log.

![screen shot 2016-03-15 at 10 00 12 am](https://cloud.githubusercontent.com/assets/1696495/13786420/bd9911ae-ea94-11e5-9ba1-e53c06408a6e.png)

**Comment by gemfarmer** [comment]
@noahmanger I'm not entirely sure why this was happening, but I don't see it as an issue anymore because the page loading was refactored (#81). Shall we close this for now and reopen if it crops up again?

**Comment by noahmanger** [comment]
Works for me!
