### ISSUE TITLE
Visual Bug: some admin icons misaligned

### ISSUE THREAD

**Issue by gemfarmer** [18F/forecast#77]
See trello: https://trello.com/c/d347tzV8/117-visual-bug-some-icons-misaligned-on-admin

<img width="29" alt="screen shot 2016-03-23 at 12 37 46 pm" src="https://cloud.githubusercontent.com/assets/4803473/13994729/222a16ee-f0f4-11e5-83e4-e5e2cf0f3114.png">
<img width="111" alt="screen shot 2016-03-23 at 12 37 25 pm" src="https://cloud.githubusercontent.com/assets/4803473/13994728/222826e0-f0f4-11e5-9b1d-e1b9bcda727c.png">

**Comment by allalala** [comment]
This issue is fixed by #79, correct?

**Comment by gemfarmer** [comment]
correct!
